[tool.poe.tasks]
fmt = "ruff format"

[tool.poe.tasks.run-example-backend]
help = "Run the Backend"
cwd  = "examples/backend"
cmd = "fastapi dev src/backend/main.py"


[tool.poe.tasks.run-example-frontend]
help = "Run the Frontend"
cwd  = "examples/frontend"
cmd = "npm run dev"